### ISSUE TITLE
SyntaxError: Unexpected Token <

### ISSUE THREAD

**Issue by XxXCobraXxX** [coinigy/google_spreadsheets#3]
Hi @ all.

I have the problem that 90% of the refreshs (CoinigyRefresh) fails with the SyntaxError described in the Title.

It's this line in Scripteditor: 

> return  JSON.parse(jsondata.getContentText()); 

Can anyone help me?

THX

**Comment by omidedipidizi** [comment]
Same here !!!!!

**Comment by robborden** [comment]
Please give an example of the output and mention what exchange(s) you're having the issue on.

**Comment by XxXCobraXxX** [comment]
Hi robborden

I have attached a Screenshot from mobile. The same issue is also on the Desktop computer.
Sometimes the output is correct but mostly (about 90%) there is that #ERROR in the cells. 

I use only Bittrex. 

Best regards 

![screenshot_20171217-143257](https://user-images.githubusercontent.com/24992014/34079956-757901f2-e337-11e7-9f6f-86e8040b58c6.png)

**Comment by robborden** [comment]
Did you modify the content of the A1 cell?  Try just using =CoinigyGetAccounts().

**Comment by XxXCobraXxX** [comment]
That is the solution!

I have copied the original Cell "A1" over mine and i use now only 

> =CoinigyGetAccounts()

 instead of 

> =CoinigyGetAccounts(A1)

 and now the script runs perfect!!!

@robborden: Thank you very much!!! :-)

**Comment by robborden** [comment]
Good to hear! Thanks for reporting back.
